feat/Wow Best Deals
ff14-advanced-market-search/saddlebag-with-pockets pull request #287
Opened 2023-07-13 22:08 UTC by krz0001

## Why

Implements WoW Best deals page from the temp frontend.

## Related Tickets

* Closes https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/issues/277

2023-07-13 22:10 UTC, maxencelav commented on app/routes/wow._index.tsx
> +    href: '/wow/export-search'
Copy/pasted a bit too quick there 😅

2023-07-13 22:11 UTC, krz0001 commented on app/routes/wow._index.tsx
> +    href: '/wow/export-search'
Copy/pasted a bit too quick there 😅 Doing a bit more fixes as it doesn't seem to appear in the sidebar for me.

2023-07-13 23:08 UTC, oldben87 requested changes

2023-07-13 23:08 UTC, oldben87 commented on app/requests/WoW/BestDeals.ts
> +  console.log('floatingSalesPerDay', floatingSalesPerDay)
Can remove the console log

2023-07-13 23:08 UTC, oldben87 commented on app/routes/wow.best-deals.tsx
> +  console.log({
Can remove the console.log

2023-07-13 23:09 UTC, oldben87 commented
> LGTM, @oldben87 give it a quick look.  Im down to merge this in tomorrow once you have a chance to see it.

Once the console.logs are removed it looks good to merge!

2023-07-14 18:35 UTC, oldben87 approved these changes

2023-07-14 18:35 UTC, merged